### ISSUE TITLE
FileExist=Append is not implemented

### ISSUE THREAD

**Issue by sarungundram** [jborza/camel-smbj#15]
When passing the parameter FileExist=Append and if the file already exists, SMB throws an exception STATUS_OBJECT_NAME_COLLISION.
Camel JCIFS used to support the file append operation. Do you have any plans to add the support for 'append'?

**Comment by jborza** [comment]
Hi,
I'll take a look at this issue.

**Comment by jborza** [comment]
Hi @sarungundram - I implemented this option, and it will be released in camel-smbj 0.2.1 soon.

Regards,
Juraj

**Comment by sarungundram** [comment]
Juraj, 
Thanks for the quick fix. Much appreciated.
