### ISSUE TITLE
the Scheduler won't work

### ISSUE THREAD

**Issue by ashenp** [jborza/camel-smbj#24]
I try to build this camel component with smbj 0.10.0， found that the Scheduler doesn't work.
Here is the code below:
`CamelContext context = new DefaultCamelContext();
            context.addComponent("smb2", new SmbComponent());
            context.addRoutes(new RouteBuilder() {
                @Override
                public void configure() throws Exception {
                    from("smb2://public:password@127.0.0.1/public/?delay=3000").to("file:data/outbox");
                }
            });
            context.start();`

When run this camel context the VM just disconnected,  without camel context shutdown, just went out:
Connected to the target VM, address: '127.0.0.1:55794', transport: 'socket'
[                          main] DefaultCamelContext            INFO  Apache Camel 2.21.0.appconnect-1.0.0-SNAPSHOT (CamelContext: camel-1) is starting
[                          main] ManagedManagementStrategy      INFO  JMX is enabled
[                          main] DefaultTypeConverter           INFO  Type converters loaded (core: 194, classpath: 0)
[                          main] DefaultCamelContext            INFO  StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[                          main] Connection                     INFO  Successfully connected to: 112.126.5.57
[                          main] Connection                     INFO  Successfully authenticated public on 112.126.5.57, session is 4284008678
[                          main] Session                        INFO  Connecting to \\112.126.5.57\public on session 4284008678
[                          main] Connection                     INFO  Closed connection to 112.126.5.57
[Packet Reader for 112.126.5.57] PacketReader                   INFO  Thread[Packet Reader for 112.126.5.57,5,main] stopped.
[                          main] DefaultCamelContext            INFO  Route: route1 started and consuming from: smb2://public:xxxxxx@112.126.5.57:139/public/?delay=3000
[                          main] DefaultCamelContext            INFO  Total 1 routes, of which 1 are started
[                          main] DefaultCamelContext            INFO  Apache Camel 2.21.0.appconnect-1.0.0-SNAPSHOT (CamelContext: camel-1) started in 0.932 seconds
Disconnected from the target VM, address: '127.0.0.1:55794', transport: 'socket'

Process finished with exit code 0

**Comment by ashenp** [comment]
I mean how to block the main thread, while route has started?  Is Thread.sleep() the only way?

**Comment by jborza** [comment]
Hi,
that's a more general Camel question, I used Thread.sleep in integration tests to make things simple.
For a more general approach use the Camel Main class, where you build the routes and then call .run():

https://people.apache.org/~dkulp/camel/running-camel-standalone-and-have-it-keep-running.html
